In [1]:
import pandas as pd
from BRL import *
from optimizer2 import solve

In [2]:
data = pd.read_excel('./data/data.xlsx', index_col=0)

In [3]:
data.drop(index=56, inplace=True)

In [4]:
tests = data.iloc[:,1:].values

In [5]:
tests

array([[ 236,  251,  253, ...,  279,  140,  183],
       [ 211,  190,  164, ...,  243,  126,  138],
       [ 145,  161,  115, ...,  173,   83,   94],
       ...,
       [ 845,  799, 1163, ..., 1144,  534,  607],
       [ 682,  659,  956, ...,  938,  449,  489],
       [ 429,  452,  555, ...,  600,  347,  355]])

{'w2': 607.0, 'w3': 51.0, 'w5': 456.0, 'w6': 8.0, 'w8': 960.0, 'w9': 66.0}

In [6]:
import numpy as np
errors = []
for test in tests:
    solution = solve(e_T=test, w2=607, w3=51, w5=456, w6=8, w8=960, w9=66)
    x = np.zeros(66)
    if bool(solution):
        for i in solution:
            x[i] = solution[i]
        e = p_matrix@x
        print(e)
        error = np.linalg.norm(test-e)
        errors.append(error)

[236. 251. 253. 254. 265. 279. 261. 279. 140. 183.]
[211. 190. 164. 192. 184. 241. 208. 243. 126. 138.]
[145. 161. 115. 200. 152. 184. 151. 173.  83.  94.]
[162. 170. 105. 185. 119. 152. 196. 141.  59.  86.]
[200. 299. 151.  47. 181. 289. 362. 207. 135. 169.]
[ 374.  783.  331.  898.  437.  681. 1096.  533.  319.  323.]
[ 633. 1207.  558. 1414.  966. 1033. 1599.  835.  487.  646.]
[1004. 1392.  866. 1619. 1552. 1249. 1769. 1340.  695. 1321.]
[1063. 1522. 1209. 1654. 1982. 1456. 1795. 1541. 1001. 1487.]
[ 981. 1309. 1139. 1570. 1559. 1326. 1627. 1524.  872. 1038.]
[1011. 1190. 1199. 1544. 1389. 1555. 1381. 1393.  828.  931.]
[ 982. 1119. 1218. 1499. 1314. 1474. 1346. 1412.  829.  780.]
[ 923. 1139. 1108. 1431. 1211. 1316. 1317. 1249.  828.  763.]
[ 817. 1109. 1226. 1378. 1466. 1332. 1374. 1322.  788.  770.]
[1013. 1118. 1291. 1448. 1468. 1369. 1260. 1421.  808.  823.]
[1161. 1121. 1445. 1446. 1443. 1440. 1303. 1519.  894.  864.]
[1208. 1119. 1608. 1510. 1517. 1636. 1384. 1590. 1016.  94

In [8]:
np.sum(errors)

0.0