In [1]:
from BRL import *
from optimizer2 import solve
import numpy as np

In [2]:
traffic_volume = {
    'r1_0_1': 1005,
    'r1_1_0': 1553,
    'r2_1_2': 1180,
    'r2_2_1': 1682,
    'r3_2_3': 1911,
    'r3_3_2': 1424,
    'r4_3_4': 1628,
    'r4_4_3': 1494,
    'r5_4_1': 1084,
    'r5_1_4': 1454
}

In [3]:
e_T = [1005,1553,1180,1682,1911,1424,1628,1494,1084,1454]

In [4]:
solution = solve(e_T=e_T, w2=626, w3=11, w5=1, w6=12, w8=288, w9=78)
x = np.zeros(66)
for i in solution:
    x[i] = solution[i]
e = p_matrix@x
print(e)
print(e_T)
print(np.linalg.norm(e_T-e))

[1005. 1553. 1180. 1682. 1911. 1424. 1628. 1494. 1084. 1454.]
[1005, 1553, 1180, 1682, 1911, 1424, 1628, 1494, 1084, 1454]
0.0


In [5]:
x

array([   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0., 1005.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0., 1553.,
          0., 1454.,    0.,    0.,    0.,    0., 1180.,    0.,    0.,
        258.,    0.,    0.,    0.,    0.,    0.,  731.,    0.,    0.,
       1084.,    0.,    0., 1494.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0., 1628.,    0.,    0.,    0.,    0.,    0.,    0., 1424.,
          0.,    0.,    0.])

In [6]:
I_matrix@x

array([   0., 1005., 4187.,  989., 1424., 1628.,    0., 2578.])

In [7]:
O_matrix@x

array([   0., 1553., 3771.,    0., 1911., 1494.,    0., 3082.])

In [8]:
from input_output_gen import data_gen

In [9]:
traffic_count = data_gen(traffic_volume=traffic_volume)

In [10]:
input_answer = []
output_answer = []

In [11]:
for edge in traffic_count:
    input_answer.append(traffic_count[edge]['enter'])
    output_answer.append(traffic_count[edge]['exit'])

In [12]:
input_answer

[502, 502, 4187, 3593, 1289, 1289, 1526, 1526]

In [13]:
output_answer

[776, 776, 3771, 2604, 1541, 1541, 1702, 1702]

## 풀어보기

In [14]:
from optimizer3 import solve

In [15]:
status, solver = solve(e_T=e_T)

In [17]:
solver.Value(x)

TypeError: Cannot interpret [   0.    0.    0.    0.    0.    0.    0.    0. 1005.    0.    0.    0.
    0.    0.    0.    0.    0. 1553.    0. 1454.    0.    0.    0.    0.
 1180.    0.    0.  258.    0.    0.    0.    0.    0.  731.    0.    0.
 1084.    0.    0. 1494.    0.    0.    0.    0.    0.    0.    0.    0.
    0.    0.    0.    0.    0.    0.    0. 1628.    0.    0.    0.    0.
    0.    0. 1424.    0.    0.    0.] as a linear expression.