In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('./data/data.xlsx', index_col=0)
data.head()

0    1    2    3    4    5    6    7    8    9    10
0  2023-04-24 00시  236  251  253  254  265  279  261  279  140  183
1  2023-04-24 01시  211  190  164  192  184  241  208  243  126  138
2  2023-04-24 02시  145  161  115  200  152  184  151  173   83   94
3  2023-04-24 03시  162  170  105  185  119  152  196  141   59   86
4  2023-04-24 04시  200  299  151   47  181  289  362  207  135  169

In [3]:
train_eT = np.array(data.iloc[56,1:].values)
train_eT

array([1005, 1553, 1180, 1682, 1911, 1424, 1628, 1494, 1084, 1454],
      dtype=object)

In [4]:
from BRL import p_matrix, I_matrix, O_matrix
from optimizer3 import solve

In [5]:
from hyperopt import hp, fmin, tpe, Trials

def objective(args):
    w2, w3, w5, w6, w8, w9 = args
    solution = solve(e_T=train_eT, w2=int(w2), w3=int(w3), w5=int(w5), w6=int(w6), w8=int(w8), w9=int(w9))
    if bool(solution): # 해가 존재
        x = np.zeros(66)
        for i in solution:
            x[i] = solution[i]
        e = p_matrix @ x
        diff = np.linalg.norm(train_eT - e)
        return diff
    else: # 해가 존재하지 않음
        return np.Inf

space = [
    hp.quniform('w2', 1, 999, 1),
    hp.quniform('w3', 1, 999, 1),
    hp.quniform('w5', 1, 999, 1),
    hp.quniform('w6', 1, 999, 1),
    hp.quniform('w8', 1, 999, 1),
    hp.quniform('w9', 1, 999, 1),
]

results = []
for i in range(100):
    try:
        trials = Trials()
        result = fmin(
            fn=objective,
            space=space,
            algo=tpe.suggest,
            max_evals=50
        )
        
        results.append(result)
    except Exception as e:
        print(f"Iteration {i}: 에러가 발생했습니다. 다음 반복으로 이동합니다. 오류 내용: {e}")

100%|██████████| 50/50 [00:04<00:00, 11.94trial/s, best loss: inf]


In [8]:
len(results)

100

In [12]:
errors = []
for result in results:
    solution = solve(e_T=train_eT, w2=int(result['w2']), w3=int(result['w3']), w5=int(result['w5']),\
        w6=int(result['w6']), w8=int(result['w8']), w9=int(result['w9']))
    x = np.zeros(66)
    for i in solution:
        x[i] = solution[i]
    e = p_matrix @ x
    errors.append(np.linalg.norm(train_eT - e))

In [16]:
errors

[548.1450537950699,
 548.1450537950699,
 2476.712740710961,
 548.1450537950699,
 548.1450537950699,
 0.0,
 1916.8268049043972,
 548.1450537950699,
 548.1450537950699,
 548.1450537950699,
 548.1450537950699,
 1742.9288568383965,
 1742.9288568383965,
 67.80855403265875,
 2476.712740710961,
 548.1450537950699,
 548.1450537950699,
 548.1450537950699,
 548.1450537950699,
 1742.9288568383965,
 2476.712740710961,
 0.0,
 548.1450537950699,
 548.1450537950699,
 548.1450537950699,
 548.1450537950699,
 548.1450537950699,
 1784.5825842476443,
 2476.712740710961,
 548.1450537950699,
 1742.9288568383965,
 1950.4381559024116,
 0.0,
 548.1450537950699,
 548.1450537950699,
 548.1450537950699,
 0.0,
 139.65314174768858,
 1950.4381559024116,
 1.4142135623730951,
 548.1450537950699,
 0.0,
 1958.9515052701024,
 1742.9288568383965,
 2476.712740710961,
 1742.9288568383965,
 2476.712740710961,
 548.1450537950699,
 1954.51579681516,
 548.1450537950699,
 1950.4381559024116,
 548.1450537950699,
 2476.71274071096

In [26]:
zeros = [i for i, error in enumerate(errors) if error == 0.0]
optimal = []
for zero in zeros:
    optimal.append(results[zero])

In [28]:
import pickle
with open('zeros.pickle', 'wb') as f:
    pickle.dump(optimal, f)

In [29]:
with open('zeros.pickle', 'rb') as f:
    zz = pickle.load(f)
print(zz)

[{'w2': 626.0, 'w3': 11.0, 'w5': 1.0, 'w6': 12.0, 'w8': 280.0, 'w9': 78.0}, {'w2': 384.0, 'w3': 21.0, 'w5': 71.0, 'w6': 49.0, 'w8': 559.0, 'w9': 62.0}, {'w2': 783.0, 'w3': 1.0, 'w5': 767.0, 'w6': 7.0, 'w8': 26.0, 'w9': 69.0}, {'w2': 943.0, 'w3': 3.0, 'w5': 739.0, 'w6': 2.0, 'w8': 30.0, 'w9': 33.0}, {'w2': 986.0, 'w3': 1.0, 'w5': 33.0, 'w6': 2.0, 'w8': 574.0, 'w9': 17.0}, {'w2': 42.0, 'w3': 29.0, 'w5': 406.0, 'w6': 51.0, 'w8': 262.0, 'w9': 24.0}, {'w2': 426.0, 'w3': 3.0, 'w5': 994.0, 'w6': 23.0, 'w8': 16.0, 'w9': 33.0}, {'w2': 225.0, 'w3': 81.0, 'w5': 561.0, 'w6': 8.0, 'w8': 561.0, 'w9': 32.0}, {'w2': 80.0, 'w3': 54.0, 'w5': 542.0, 'w6': 83.0, 'w8': 552.0, 'w9': 20.0}, {'w2': 607.0, 'w3': 51.0, 'w5': 456.0, 'w6': 8.0, 'w8': 960.0, 'w9': 66.0}, {'w2': 822.0, 'w3': 72.0, 'w5': 298.0, 'w6': 8.0, 'w8': 919.0, 'w9': 65.0}, {'w2': 51.0, 'w3': 42.0, 'w5': 833.0, 'w6': 4.0, 'w8': 805.0, 'w9': 14.0}, {'w2': 559.0, 'w3': 26.0, 'w5': 81.0, 'w6': 26.0, 'w8': 667.0, 'w9': 47.0}]


In [15]:
solution = solve(e_T=train_eT, w2=626, w3=11, w5=1, w6=12, w8=288, w9=78)
x = np.zeros(66)
for i in solution:
    x[i] = solution[i]
e = p_matrix@x
print(e)
print(train_eT)
print(np.linalg.norm(train_eT-e))

[1005. 1553. 1180. 1682. 1911. 1424. 1628. 1494. 1084. 1454.]
[1005 1553 1180 1682 1911 1424 1628 1494 1084 1454]
0.0
