In [1]:
from BRL import *
from optimizer2 import solve
import numpy as np

In [2]:
traffic_volume = {
    'r1_0_1': 1005,
    'r1_1_0': 1553,
    'r2_1_2': 1180,
    'r2_2_1': 1682,
    'r3_2_3': 1911,
    'r3_3_2': 1424,
    'r4_3_4': 1628,
    'r4_4_3': 1494,
    'r5_4_1': 1084,
    'r5_1_4': 1454
}

In [3]:
test = [1005,1553,1180,1682,1911,1424,1628,1494,1084,1454]

In [4]:
solution = solve(e_T=test, w2=626, w3=11, w5=1, w6=12, w8=288, w9=78)
x = np.zeros(66)
for i in solution:
    x[i] = solution[i]
e = p_matrix@x
print(e)
print(test)
print(np.linalg.norm(test-e))

[1005. 1553. 1180. 1682. 1911. 1424. 1628. 1494. 1084. 1454.]
[1005, 1553, 1180, 1682, 1911, 1424, 1628, 1494, 1084, 1454]
0.0


In [5]:
x

array([   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0., 1005.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0., 1553.,
          0., 1454.,    0.,    0.,    0.,    0., 1180.,    0.,    0.,
        258.,    0.,    0.,    0.,    0.,    0.,  731.,    0.,    0.,
       1084.,    0.,    0., 1494.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0., 1628.,    0.,    0.,    0.,    0.,    0.,    0., 1424.,
          0.,    0.,    0.])

In [6]:
I_matrix@x

array([   0., 1005., 4187.,  989., 1424., 1628.,    0., 2578.])

In [7]:
O_matrix@x

array([   0., 1553., 3771.,    0., 1911., 1494.,    0., 3082.])

## 풀어보기

In [8]:
from optimizer4 import solve

In [9]:
solve(e_T=test)

inf