In [1]:
import pandas as pd
import numpy as np

In [2]:
input_volumes = pd.read_excel('./data/input_volume.xlsx', index_col=0)
input_volumes.head()

0_0  0_2  1_3  2_2  3_2  3_1  4_1  4_2
0  295  491  158  254  208  232  300  252
1  216  437  103  226  189  141  185  220
2  195  314   93  197  147  128  187  147
3  205  352   68  256  204  119  258  143
4  482  520  161  438  313  335  747  205

In [3]:
input_volume = input_volumes.iloc[56, :].values
input_volume

array([1549, 2560, 1157, 2065, 1801, 1514, 1842, 1211], dtype=int64)

In [4]:
tests = pd.read_excel('./data/data.xlsx', index_col=0)
tests.head()

0    1    2    3    4    5    6    7    8    9    10
0  2023-04-24 00시  236  251  253  254  265  279  261  279  140  183
1  2023-04-24 01시  211  190  164  192  184  241  208  243  126  138
2  2023-04-24 02시  145  161  115  200  152  184  151  173   83   94
3  2023-04-24 03시  162  170  105  185  119  152  196  141   59   86
4  2023-04-24 04시  200  299  151   47  181  289  362  207  135  169

In [5]:
test = tests.iloc[56,1:].values
test

array([1005, 1553, 1180, 1682, 1911, 1424, 1628, 1494, 1084, 1454],
      dtype=object)

In [6]:
from optimizer3 import *

In [7]:
solution = solve(e_T=test, input_volume=input_volume)

In [8]:
x = np.zeros(66)
for i in solution:
    x[i] = solution[i]
e = p_matrix@x
input_generated = I_matrix@x
print(e)
print(test)
print('-------------------')
print(input_volume)
print(input_generated)

[1040. 1553. 1180. 1688. 1863. 1450. 1627. 1557. 1267. 1471.]
[1005 1553 1180 1682 1911 1424 1628 1494 1084 1454]
-------------------
[1549, 2560, 1157, 2065, 1801, 1514, 1842, 1211]
[   0. 1040. 1157. 1982. 1028. 1253. 1470.  508.]
