In [1]:
from optimizer_apms import solve
from apms import *
import pandas as pd
import numpy as np
data = pd.read_excel('./data.xlsx', index_col=0)
tests = data.iloc[:,1:].values

In [3]:
inputs = pd.read_excel('./input_volume.xlsx', index_col=0)

In [12]:
outputs = pd.read_excel('./output_volume.xlsx', index_col=0)

In [2]:
result , status = solve(e_T=tests[56])
status
# x = np.zeros(72)
# for i in solution:
#     x[i] = solution[i]

2

In [6]:
result

{0: 8,
 1: 1,
 2: 1,
 3: 1,
 4: 1,
 6: 3,
 7: 1,
 8: 3,
 9: 47,
 10: 47,
 11: 47,
 12: 47,
 13: 47,
 14: 75,
 15: 280,
 16: 74,
 17: 276,
 18: 3,
 19: 3,
 20: 3,
 21: 4,
 22: 3,
 23: 7,
 24: 15,
 25: 7,
 26: 15,
 27: 7,
 28: 34,
 29: 7,
 30: 13,
 31: 22,
 32: 18,
 33: 20,
 34: 11,
 35: 8,
 36: 10,
 37: 116,
 38: 10,
 39: 15,
 41: 10,
 42: 19,
 43: 20,
 44: 56,
 45: 428,
 46: 56,
 47: 175,
 49: 56,
 50: 175,
 51: 174,
 53: 4,
 55: 56,
 56: 4,
 58: 4,
 59: 4,
 60: 4,
 61: 4,
 63: 58,
 64: 181,
 65: 631,
 67: 58,
 68: 58,
 69: 58,
 70: 58,
 71: 58}

In [7]:
x = np.zeros(72)
for i in result:
    x[i] = result[i]

In [9]:
p_matrix@x

array([ 904., 1587.,  643.,  886.,  653., 1059.,  351.,  742.,  861.,
        298.])

In [11]:
inputs.iloc[56,1:]

0_2    2560
1_3    1157
2_2    2065
3_2    1801
3_1    1514
4_1    1842
4_2    1211
Name: 56, dtype: int64

In [17]:
tests[56]

array([1005, 1553, 1180, 1682, 1911, 1424, 1628, 1494, 1084, 1454],
      dtype=int64)

In [15]:
I_matrix@x

array([  19.,  940.,   60.,  140., 1160.,   80., 1120.,  200.])

In [14]:
outputs.iloc[56,1:]

0_2     998
1_3    1157
2_2    2078
3_2    1427
3_1    2210
4_1    1730
4_0    1671
Name: 56, dtype: int64

In [16]:
O_matrix@x

array([ 185., 1457.,  183.,  303.,  582.,  643.,  161.,  205.])

In [17]:
tests[56]

array([1005, 1553, 1180, 1682, 1911, 1424, 1628, 1494, 1084, 1454],
      dtype=int64)

In [6]:
I_matrix@x

array([  79.,  820.,   20.,   60., 1420., 1060.,  180.,  140.])

In [7]:
result = return_results(x)
result

{('0_0', '0_2'): 32.0,
 ('0_0', '1_3'): 4.0,
 ('0_0', '2_2'): 4.0,
 ('0_0', '4_0'): 4.0,
 ('0_0', '4_1'): 4.0,
 ('0_0', '3_1'): 15.0,
 ('0_0', '3_2'): 16.0,
 ('0_2', '0_0'): 41.0,
 ('0_2', '1_3'): 41.0,
 ('0_2', '2_2'): 41.0,
 ('0_2', '4_0'): 41.0,
 ('0_2', '4_1'): 41.0,
 ('0_2', '3_1'): 308.0,
 ('0_2', '3_2'): 307.0,
 ('1_3', '0_0'): 1.0,
 ('1_3', '0_2'): 1.0,
 ('1_3', '2_2'): 1.0,
 ('1_3', '4_0'): 1.0,
 ('1_3', '4_1'): 1.0,
 ('1_3', '3_1'): 9.0,
 ('1_3', '3_2'): 6.0,
 ('2_2', '0_0'): 3.0,
 ('2_2', '0_2'): 3.0,
 ('2_2', '1_3'): 3.0,
 ('2_2', '4_0'): 27.0,
 ('2_2', '4_1'): 18.0,
 ('2_2', '3_1'): 3.0,
 ('2_2', '3_2'): 3.0,
 ('4_0', '0_0'): 7.0,
 ('4_0', '0_2'): 7.0,
 ('4_0', '1_3'): 7.0,
 ('4_0', '2_2'): 67.0,
 ('4_0', '4_1'): 7.0,
 ('4_0', '3_1'): 38.0,
 ('4_0', '3_2'): 7.0,
 ('4_1', '0_0'): 9.0,
 ('4_1', '0_2'): 13.0,
 ('4_1', '1_3'): 9.0,
 ('4_1', '2_2'): 79.0,
 ('4_1', '4_0'): 9.0,
 ('4_1', '3_1'): 9.0,
 ('4_1', '3_2'): 52.0,
 ('3_1', '0_0'): 53.0,
 ('3_1', '0_2'): 584.0,
 ('3_1', '

In [9]:
result = return_ratio(result)

In [10]:
result

{(0, 1): 40.51,
 (0, 2): 5.06,
 (0, 3): 5.06,
 (0, 7): 5.06,
 (0, 6): 5.06,
 (0, 5): 18.99,
 (0, 4): 20.25,
 (1, 0): 5.0,
 (1, 2): 5.0,
 (1, 3): 5.0,
 (1, 7): 5.0,
 (1, 6): 5.0,
 (1, 5): 37.56,
 (1, 4): 37.44,
 (2, 0): 5.0,
 (2, 1): 5.0,
 (2, 3): 5.0,
 (2, 7): 5.0,
 (2, 6): 5.0,
 (2, 5): 45.0,
 (2, 4): 30.0,
 (3, 0): 5.0,
 (3, 1): 5.0,
 (3, 2): 5.0,
 (3, 7): 45.0,
 (3, 6): 30.0,
 (3, 5): 5.0,
 (3, 4): 5.0,
 (7, 0): 5.0,
 (7, 1): 5.0,
 (7, 2): 5.0,
 (7, 3): 47.86,
 (7, 6): 5.0,
 (7, 5): 27.14,
 (7, 4): 5.0,
 (6, 0): 5.0,
 (6, 1): 7.22,
 (6, 2): 5.0,
 (6, 3): 43.89,
 (6, 7): 5.0,
 (6, 5): 5.0,
 (6, 4): 28.89,
 (5, 0): 5.0,
 (5, 1): 55.09,
 (5, 2): 17.55,
 (5, 3): 5.0,
 (5, 7): 6.79,
 (5, 6): 5.28,
 (5, 4): 5.28,
 (4, 0): 5.0,
 (4, 1): 63.66,
 (4, 2): 11.34,
 (4, 3): 5.0,
 (4, 7): 5.0,
 (4, 6): 5.0,
 (4, 5): 5.0}

In [12]:
df = pd.DataFrame(list(result.items()), columns=['Index', 'Value'])

# Split the Index column into two separate columns
df[['First_Index', 'Second_Index']] = pd.DataFrame(df['Index'].tolist(), index=df.index)

# Drop the original Index column
df = df.drop('Index', axis=1)

# Reorder the columns
df = df[['First_Index', 'Second_Index', 'Value']]

# Sort the DataFrame by the indices
df = df.sort_values(by=['First_Index', 'Second_Index']).reset_index(drop=True)

print(df)

    First_Index  Second_Index  Value
0             0             1  40.51
1             0             2   5.06
2             0             3   5.06
3             0             4  20.25
4             0             5  18.99
5             0             6   5.06
6             0             7   5.06
7             1             0   5.00
8             1             2   5.00
9             1             3   5.00
10            1             4  37.44
11            1             5  37.56
12            1             6   5.00
13            1             7   5.00
14            2             0   5.00
15            2             1   5.00
16            2             3   5.00
17            2             4  30.00
18            2             5  45.00
19            2             6   5.00
20            2             7   5.00
21            3             0   5.00
22            3             1   5.00
23            3             2   5.00
24            3             4   5.00
25            3             5   5.00
2