In [1]:
import pandas as pd
import numpy as np
from BRL2 import *

In [2]:
data = pd.read_excel('./data/data.xlsx', index_col=0)

In [3]:
tests = data.loc[:,1:].values
tests.shape

(120, 10)

In [4]:
a = [1, 2, 3]
a.index(2)

1

In [5]:
from optimizer2 import solve

In [7]:
len(all_shortest_paths)

72

In [9]:
solution

{0: 10000,
 17: 236,
 19: 251,
 22: 183,
 26: 17,
 35: 12,
 38: 140,
 42: 279,
 49: 1,
 59: 261,
 67: 254,
 68: 25}

In [10]:
import numpy as np
input_volumes = [[]*13]
# for k in range(len(zeros)):
temp = []
for test in tests:
    solution = solve(e_T=test)
    x = np.zeros(72)
    for i in solution:
        x[i] = solution[i]
    input_volume = I_matrix@x
    temp.append(input_volume)
pd.DataFrame(temp).to_excel(f'temp_{0}.xlsx') 

In [7]:
solution

{0: 10000,
 1: 226,
 17: 10,
 19: 1,
 22: 183,
 26: 243,
 29: 1,
 35: 12,
 38: 140,
 42: 279,
 49: 1,
 59: 261,
 65: 250,
 67: 3,
 68: 26}

In [ ]:
solution

4

In [ ]:
temp

[array([  0., 236., 687., 162., 279., 261.,   0., 419.]),
 array([  0., 211., 492.,  20., 241., 208.,   0., 369.]),
 array([  0., 145., 370.,  53., 184., 151.,   0., 256.]),
 array([  0., 162., 361.,  48., 152., 196.,   0., 200.]),
 array([  0., 200., 619.,  30., 280., 362.,   0., 342.]),
 array([   0.,  374., 1437.,  554.,  681., 1096.,    0.,  852.]),
 array([   0.,  633., 2411.,  789., 1033., 1599.,    0., 1322.]),
 array([   0., 1004., 3579., 1056., 1249., 1769.,    0., 2035.]),
 array([   0., 1063., 4218.,  971., 1456., 1795.,    0., 2542.]),
 array([   0.,  981., 3486.,  664., 1326., 1627.,    0., 2396.]),
 array([   0., 1011., 3320., 1735., 1555., 1381.,    0., 2221.]),
 array([   0.,  982., 3117.,  121., 1474., 1346.,    0., 2241.]),
 array([   0.,  923., 3010.,  218., 1316., 1317.,    0., 2077.]),
 array([   0.,  817., 3105., 1237., 1332., 1374.,    0., 2110.]),
 array([   0., 1013., 3232.,  256., 1369., 1260.,    0., 2229.]),
 array([   0., 1161., 3430., 1233., 1440., 1303., 