In [1]:
from optimizer4 import solve
from BRL import *

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_excel('./data/data.xlsx', index_col=0)
data.head()

0    1    2    3    4    5    6    7    8    9    10
0  2023-04-24 00시  236  251  253  254  265  279  261  279  140  183
1  2023-04-24 01시  211  190  164  192  184  241  208  243  126  138
2  2023-04-24 02시  145  161  115  200  152  184  151  173   83   94
3  2023-04-24 03시  162  170  105  185  119  152  196  141   59   86
4  2023-04-24 04시  200  299  151   47  181  289  362  207  135  169

In [4]:
tests = data.iloc[:,1:].values
tests

array([[ 236,  251,  253, ...,  279,  140,  183],
       [ 211,  190,  164, ...,  243,  126,  138],
       [ 145,  161,  115, ...,  173,   83,   94],
       ...,
       [ 845,  799, 1163, ..., 1144,  534,  607],
       [ 682,  659,  956, ...,  938,  449,  489],
       [ 429,  452,  555, ...,  600,  347,  355]])

In [10]:
tests[56]

array([1005, 1553, 1180, 1682, 1911, 1424, 1628, 1494, 1084, 1454])

In [5]:
solution = solve(e_T=tests[56])
x = np.zeros(66)
for i in solution:
    x[i] = solution[i]

In [12]:
p_matrix@x

array([1008., 1552., 1161., 1672., 1884., 1416., 1618., 1484., 1080.,
       1438.])

In [13]:
I_matrix@x

array([ 505.,  503., 1208., 1417., 1129., 1129.,  519.,  519.])

In [6]:
def return_results(x):
    result = {}
    for i in range(len(x)):
        if x[i] != 0:
            path = all_shortest_paths[i]
            origin_edge, destination_edge = edges[path[0]][0], edges[path[-1]][-1]
            if (origin_edge, destination_edge) not in result:
                result[(origin_edge, destination_edge)] = 0
            result[(origin_edge, destination_edge)] += x[i]
    return result

In [7]:
result = return_results(x)
result

{('0_0', '4_0'): 6.0,
 ('0_0', '4_1'): 7.0,
 ('0_0', '3_1'): 245.0,
 ('0_0', '3_2'): 247.0,
 ('0_2', '4_0'): 8.0,
 ('0_2', '4_1'): 5.0,
 ('0_2', '3_1'): 245.0,
 ('0_2', '3_2'): 245.0,
 ('1_3', '0_2'): 75.0,
 ('1_3', '2_2'): 11.0,
 ('1_3', '4_0'): 109.0,
 ('1_3', '4_1'): 109.0,
 ('1_3', '3_1'): 452.0,
 ('1_3', '3_2'): 452.0,
 ('2_2', '0_2'): 150.0,
 ('2_2', '1_3'): 75.0,
 ('2_2', '4_0'): 439.0,
 ('2_2', '4_1'): 439.0,
 ('2_2', '3_1'): 161.0,
 ('2_2', '3_2'): 153.0,
 ('4_0', '0_2'): 110.0,
 ('4_0', '1_3'): 35.0,
 ('4_0', '2_2'): 178.0,
 ('4_0', '3_1'): 98.0,
 ('4_0', '3_2'): 98.0,
 ('4_1', '0_2'): 110.0,
 ('4_1', '1_3'): 35.0,
 ('4_1', '2_2'): 178.0,
 ('4_1', '3_1'): 98.0,
 ('4_1', '3_2'): 98.0,
 ('3_1', '0_0'): 67.0,
 ('3_1', '0_2'): 485.0,
 ('3_1', '1_3'): 336.0,
 ('3_1', '2_2'): 36.0,
 ('3_1', '4_0'): 104.0,
 ('3_1', '4_1'): 101.0,
 ('3_2', '0_0'): 68.0,
 ('3_2', '0_2'): 487.0,
 ('3_2', '1_3'): 336.0,
 ('3_2', '2_2'): 35.0,
 ('3_2', '4_0'): 101.0,
 ('3_2', '4_1'): 102.0}

In [8]:
def return_ratio(result):
    grouped_dict = {}

    # 딕셔너리의 키-값 쌍에 대해 반복
    for key, value in result.items():
        first_element = key[0]
        
        if first_element not in grouped_dict:
            grouped_dict[first_element] = []
        
        grouped_dict[first_element].append((key, value))

    # 비율을 저장할 딕셔너리
    ratios = {}

    # 각 그룹에 대해 반복
    for first_element, group in grouped_dict.items():
        total_value = sum(value for _, value in group)
        
        # 그룹 내의 키-값 쌍에 대해 반복하며 비율 계산
        for key, value in group:
            ratio = value / total_value
            ratios[key] = round(100*ratio, 2)
    
    updated_ratios = {}

    for key, value in ratios.items():
        first_key, second_key = key
        new_key = (node_index[first_key], node_index[second_key])
        updated_ratios[new_key] = value
    
    return updated_ratios

In [9]:
return_ratio(result)

{(0, 7): 1.19,
 (0, 6): 1.39,
 (0, 5): 48.51,
 (0, 4): 48.91,
 (1, 7): 1.59,
 (1, 6): 0.99,
 (1, 5): 48.71,
 (1, 4): 48.71,
 (2, 1): 6.21,
 (2, 3): 0.91,
 (2, 7): 9.02,
 (2, 6): 9.02,
 (2, 5): 37.42,
 (2, 4): 37.42,
 (3, 1): 10.59,
 (3, 2): 5.29,
 (3, 7): 30.98,
 (3, 6): 30.98,
 (3, 5): 11.36,
 (3, 4): 10.8,
 (7, 1): 21.19,
 (7, 2): 6.74,
 (7, 3): 34.3,
 (7, 5): 18.88,
 (7, 4): 18.88,
 (6, 1): 21.19,
 (6, 2): 6.74,
 (6, 3): 34.3,
 (6, 5): 18.88,
 (6, 4): 18.88,
 (5, 0): 5.93,
 (5, 1): 42.96,
 (5, 2): 29.76,
 (5, 3): 3.19,
 (5, 7): 9.21,
 (5, 6): 8.95,
 (4, 0): 6.02,
 (4, 1): 43.14,
 (4, 2): 29.76,
 (4, 3): 3.1,
 (4, 7): 8.95,
 (4, 6): 9.03}