In [1]:
from optimizer_apms import solve
from apms import *

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_excel('./data.xlsx', index_col=0)
data.head()

0    1    2    3    4    5    6    7    8    9    10
0  2023-04-24 00시  236  251  253  254  265  279  261  279  140  183
1  2023-04-24 01시  211  190  164  192  184  241  208  243  126  138
2  2023-04-24 02시  145  161  115  200  152  184  151  173   83   94
3  2023-04-24 03시  162  170  105  185  119  152  196  141   59   86
4  2023-04-24 04시  200  299  151   47  181  289  362  207  135  169

In [4]:
tests = data.iloc[:,1:].values
tests

array([[ 236,  251,  253, ...,  279,  140,  183],
       [ 211,  190,  164, ...,  243,  126,  138],
       [ 145,  161,  115, ...,  173,   83,   94],
       ...,
       [ 845,  799, 1163, ..., 1144,  534,  607],
       [ 682,  659,  956, ...,  938,  449,  489],
       [ 429,  452,  555, ...,  600,  347,  355]], dtype=int64)

In [5]:
tests[56]

array([1005, 1553, 1180, 1682, 1911, 1424, 1628, 1494, 1084, 1454],
      dtype=int64)

In [6]:
solution = solve(e_T=tests[56])
x = np.zeros(66)
for i in solution:
    x[i] = solution[i]

In [7]:
p_matrix@x

array([1019., 1520., 1148., 1687., 1522., 1372., 1578., 1482., 1081.,
       1406.])

In [8]:
I_matrix@x

array([ 510.,  509., 1136., 1112., 1174., 1159.,  519.,  490.])

In [9]:
def return_results(x):
    result = {}
    for i in range(len(x)):
        if x[i] != 0:
            path = all_shortest_paths[i]
            origin_edge, destination_edge = edges[path[0]][0], edges[path[-1]][-1]
            if (origin_edge, destination_edge) not in result:
                result[(origin_edge, destination_edge)] = 0
            result[(origin_edge, destination_edge)] += x[i]
    return result

In [10]:
result = return_results(x)
result

{('0_0', '4_0'): 6.0,
 ('0_0', '4_1'): 5.0,
 ('0_0', '3_1'): 250.0,
 ('0_0', '3_2'): 249.0,
 ('0_2', '4_0'): 6.0,
 ('0_2', '4_1'): 5.0,
 ('0_2', '3_1'): 250.0,
 ('0_2', '3_2'): 248.0,
 ('1_3', '0_2'): 68.0,
 ('1_3', '2_2'): 14.0,
 ('1_3', '4_0'): 97.0,
 ('1_3', '4_1'): 97.0,
 ('1_3', '3_1'): 430.0,
 ('1_3', '3_2'): 430.0,
 ('2_2', '0_2'): 163.0,
 ('2_2', '1_3'): 94.0,
 ('2_2', '4_0'): 369.0,
 ('2_2', '4_1'): 369.0,
 ('2_2', '3_1'): 59.0,
 ('2_2', '3_2'): 58.0,
 ('4_0', '0_2'): 92.0,
 ('4_0', '1_3'): 28.0,
 ('4_0', '2_2'): 172.0,
 ('4_0', '3_1'): 99.0,
 ('4_0', '3_2'): 99.0,
 ('4_1', '0_2'): 92.0,
 ('4_1', '1_3'): 38.0,
 ('4_1', '2_2'): 174.0,
 ('4_1', '3_1'): 99.0,
 ('4_1', '3_2'): 116.0,
 ('3_1', '0_0'): 65.0,
 ('3_1', '0_2'): 481.0,
 ('3_1', '1_3'): 344.0,
 ('3_1', '2_2'): 31.0,
 ('3_1', '4_0'): 119.0,
 ('3_1', '4_1'): 119.0,
 ('3_2', '0_0'): 67.0,
 ('3_2', '0_2'): 492.0,
 ('3_2', '1_3'): 345.0,
 ('3_2', '2_2'): 32.0,
 ('3_2', '4_0'): 119.0,
 ('3_2', '4_1'): 119.0}

In [11]:
def return_ratio(result):
    grouped_dict = {}

    # 딕셔너리의 키-값 쌍에 대해 반복
    for key, value in result.items():
        first_element = key[0]
        
        if first_element not in grouped_dict:
            grouped_dict[first_element] = []
        
        grouped_dict[first_element].append((key, value))

    # 비율을 저장할 딕셔너리
    ratios = {}

    # 각 그룹에 대해 반복
    for first_element, group in grouped_dict.items():
        total_value = sum(value for _, value in group)
        
        # 그룹 내의 키-값 쌍에 대해 반복하며 비율 계산
        for key, value in group:
            ratio = value / total_value
            ratios[key] = round(100*ratio, 2)
    
    updated_ratios = {}

    for key, value in ratios.items():
        first_key, second_key = key
        new_key = (node_index[first_key], node_index[second_key])
        updated_ratios[new_key] = value
    
    return updated_ratios

In [12]:
return_ratio(result)

{(0, 7): 1.18,
 (0, 6): 0.98,
 (0, 5): 49.02,
 (0, 4): 48.82,
 (1, 7): 1.18,
 (1, 6): 0.98,
 (1, 5): 49.12,
 (1, 4): 48.72,
 (2, 1): 5.99,
 (2, 3): 1.23,
 (2, 7): 8.54,
 (2, 6): 8.54,
 (2, 5): 37.85,
 (2, 4): 37.85,
 (3, 1): 14.66,
 (3, 2): 8.45,
 (3, 7): 33.18,
 (3, 6): 33.18,
 (3, 5): 5.31,
 (3, 4): 5.22,
 (7, 1): 18.78,
 (7, 2): 5.71,
 (7, 3): 35.1,
 (7, 5): 20.2,
 (7, 4): 20.2,
 (6, 1): 17.73,
 (6, 2): 7.32,
 (6, 3): 33.53,
 (6, 5): 19.08,
 (6, 4): 22.35,
 (5, 0): 5.61,
 (5, 1): 41.5,
 (5, 2): 29.68,
 (5, 3): 2.67,
 (5, 7): 10.27,
 (5, 6): 10.27,
 (4, 0): 5.71,
 (4, 1): 41.91,
 (4, 2): 29.39,
 (4, 3): 2.73,
 (4, 7): 10.14,
 (4, 6): 10.14}