In [1]:
from optimizer4 import solve
from BRL import *

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_excel('./data/data.xlsx', index_col=0)
data.head()

0    1    2    3    4    5    6    7    8    9    10
0  2023-04-24 00시  236  251  253  254  265  279  261  279  140  183
1  2023-04-24 01시  211  190  164  192  184  241  208  243  126  138
2  2023-04-24 02시  145  161  115  200  152  184  151  173   83   94
3  2023-04-24 03시  162  170  105  185  119  152  196  141   59   86
4  2023-04-24 04시  200  299  151   47  181  289  362  207  135  169

In [4]:
tests = data.iloc[:,1:].values
tests

array([[ 236,  251,  253, ...,  279,  140,  183],
       [ 211,  190,  164, ...,  243,  126,  138],
       [ 145,  161,  115, ...,  173,   83,   94],
       ...,
       [ 845,  799, 1163, ..., 1144,  534,  607],
       [ 682,  659,  956, ...,  938,  449,  489],
       [ 429,  452,  555, ...,  600,  347,  355]], dtype=int64)

In [6]:
solution = solve(e_T=tests[56])
x = np.zeros(66)
for i in solution:
    x[i] = solution[i]

In [7]:
I_matrix@x

array([ 543.,  586., 1069., 1276., 1090., 1179.,  521.,  380.])

In [12]:
O_matrix@x

array([ 136., 1433.,  784.,  432., 1239., 1274.,  670.,  676.])

In [8]:
p_matrix@x

array([1129., 1569., 1181., 1678., 1742., 1395., 1583., 1480., 1018.,
       1360.])

In [9]:
tests[56]

array([1005, 1553, 1180, 1682, 1911, 1424, 1628, 1494, 1084, 1454],
      dtype=int64)

In [10]:
x

array([  0.,   0.,   9.,   3., 114., 150., 106., 161.,   0.,   0.,   8.,
         8., 120., 185., 109., 156.,   0.,  71.,  19.,  86.,  69., 217.,
       207., 178., 222.,   0., 180., 102., 172., 211., 161., 224., 113.,
       113.,   0.,  77.,   0., 137.,   0.,  75.,  91.,   0., 107.,   0.,
       137.,  81.,  93., 103.,  36.,  69., 248., 276., 149., 204.,  29.,
        65., 103.,   0.,  31., 195., 279., 125., 204.,  29., 125., 102.])

In [11]:
all_shortest_paths

[['0_0i', '0_1o', 'r1_0_1', '1_0i', '1_3o'],
 ['0_0i', '0_1o', 'r1_0_1', '1_0i', '1_2o', 'r2_1_2', '2_0i', '2_2o'],
 ['0_0i', '0_1o', 'r1_0_1', '1_0i', '1_1o', 'r5_1_4', '4_3i', '4_0o'],
 ['0_0i', '0_1o', 'r1_0_1', '1_0i', '1_1o', 'r5_1_4', '4_3i', '4_1o'],
 ['0_0i',
  '0_1o',
  'r1_0_1',
  '1_0i',
  '1_1o',
  'r5_1_4',
  '4_3i',
  '4_2o',
  'r4_4_3',
  '3_0i',
  '3_1o'],
 ['0_0i',
  '0_1o',
  'r1_0_1',
  '1_0i',
  '1_2o',
  'r2_1_2',
  '2_0i',
  '2_1o',
  'r3_2_3',
  '3_3i',
  '3_1o'],
 ['0_0i',
  '0_1o',
  'r1_0_1',
  '1_0i',
  '1_1o',
  'r5_1_4',
  '4_3i',
  '4_2o',
  'r4_4_3',
  '3_0i',
  '3_2o'],
 ['0_0i',
  '0_1o',
  'r1_0_1',
  '1_0i',
  '1_2o',
  'r2_1_2',
  '2_0i',
  '2_1o',
  'r3_2_3',
  '3_3i',
  '3_2o'],
 ['0_2i', '0_1o', 'r1_0_1', '1_0i', '1_3o'],
 ['0_2i', '0_1o', 'r1_0_1', '1_0i', '1_2o', 'r2_1_2', '2_0i', '2_2o'],
 ['0_2i', '0_1o', 'r1_0_1', '1_0i', '1_1o', 'r5_1_4', '4_3i', '4_0o'],
 ['0_2i', '0_1o', 'r1_0_1', '1_0i', '1_1o', 'r5_1_4', '4_3i', '4_1o'],
 ['0_2i',
  '0_1

In [18]:
result = {}
for i in range(len(x)):
    if x[i] != 0:
        path = all_shortest_paths[i]
        origin_edge, destination_edge = edges[path[0]][0], edges[path[-1]][-1]
        if (origin_edge, destination_edge) not in result:
            result[(origin_edge, destination_edge)] = 0
        result[(origin_edge, destination_edge)] += x[i]

In [19]:
result

{('0_0', '4_0'): 9.0,
 ('0_0', '4_1'): 3.0,
 ('0_0', '3_1'): 264.0,
 ('0_0', '3_2'): 267.0,
 ('0_2', '4_0'): 8.0,
 ('0_2', '4_1'): 8.0,
 ('0_2', '3_1'): 305.0,
 ('0_2', '3_2'): 265.0,
 ('1_3', '0_2'): 71.0,
 ('1_3', '2_2'): 19.0,
 ('1_3', '4_0'): 86.0,
 ('1_3', '4_1'): 69.0,
 ('1_3', '3_1'): 424.0,
 ('1_3', '3_2'): 400.0,
 ('2_2', '0_2'): 180.0,
 ('2_2', '1_3'): 102.0,
 ('2_2', '4_0'): 383.0,
 ('2_2', '4_1'): 385.0,
 ('2_2', '3_1'): 113.0,
 ('2_2', '3_2'): 113.0,
 ('4_0', '0_2'): 77.0,
 ('4_0', '2_2'): 137.0,
 ('4_0', '3_1'): 75.0,
 ('4_0', '3_2'): 91.0,
 ('4_1', '0_2'): 107.0,
 ('4_1', '2_2'): 218.0,
 ('4_1', '3_1'): 93.0,
 ('4_1', '3_2'): 103.0,
 ('3_1', '0_0'): 105.0,
 ('3_1', '0_2'): 524.0,
 ('3_1', '1_3'): 353.0,
 ('3_1', '2_2'): 29.0,
 ('3_1', '4_0'): 65.0,
 ('3_1', '4_1'): 103.0,
 ('3_2', '0_0'): 31.0,
 ('3_2', '0_2'): 474.0,
 ('3_2', '1_3'): 329.0,
 ('3_2', '2_2'): 29.0,
 ('3_2', '4_0'): 125.0,
 ('3_2', '4_1'): 102.0}

In [32]:
grouped_dict = {}

# 딕셔너리의 키-값 쌍에 대해 반복
for key, value in result.items():
    first_element = key[0]
    
    if first_element not in grouped_dict:
        grouped_dict[first_element] = []
    
    grouped_dict[first_element].append((key, value))

# 비율을 저장할 딕셔너리
ratios = {}

# 각 그룹에 대해 반복
for first_element, group in grouped_dict.items():
    total_value = sum(value for _, value in group)
    
    # 그룹 내의 키-값 쌍에 대해 반복하며 비율 계산
    for key, value in group:
        ratio = value / total_value
        ratios[key] = round(100*ratio, 2)

# 결과 출력
print(ratios)

{('0_0', '4_0'): 1.66, ('0_0', '4_1'): 0.55, ('0_0', '3_1'): 48.62, ('0_0', '3_2'): 49.17, ('0_2', '4_0'): 1.37, ('0_2', '4_1'): 1.37, ('0_2', '3_1'): 52.05, ('0_2', '3_2'): 45.22, ('1_3', '0_2'): 6.64, ('1_3', '2_2'): 1.78, ('1_3', '4_0'): 8.04, ('1_3', '4_1'): 6.45, ('1_3', '3_1'): 39.66, ('1_3', '3_2'): 37.42, ('2_2', '0_2'): 14.11, ('2_2', '1_3'): 7.99, ('2_2', '4_0'): 30.02, ('2_2', '4_1'): 30.17, ('2_2', '3_1'): 8.86, ('2_2', '3_2'): 8.86, ('4_0', '0_2'): 20.26, ('4_0', '2_2'): 36.05, ('4_0', '3_1'): 19.74, ('4_0', '3_2'): 23.95, ('4_1', '0_2'): 20.54, ('4_1', '2_2'): 41.84, ('4_1', '3_1'): 17.85, ('4_1', '3_2'): 19.77, ('3_1', '0_0'): 8.91, ('3_1', '0_2'): 44.44, ('3_1', '1_3'): 29.94, ('3_1', '2_2'): 2.46, ('3_1', '4_0'): 5.51, ('3_1', '4_1'): 8.74, ('3_2', '0_0'): 2.84, ('3_2', '0_2'): 43.49, ('3_2', '1_3'): 30.18, ('3_2', '2_2'): 2.66, ('3_2', '4_0'): 11.47, ('3_2', '4_1'): 9.36}


In [33]:
updated_ratios = {}

for key, value in ratios.items():
    first_key, second_key = key
    new_key = (node_index[first_key], node_index[second_key])
    updated_ratios[new_key] = value

# 결과 출력
print(updated_ratios)

{(0, 7): 1.66, (0, 6): 0.55, (0, 5): 48.62, (0, 4): 49.17, (1, 7): 1.37, (1, 6): 1.37, (1, 5): 52.05, (1, 4): 45.22, (2, 1): 6.64, (2, 3): 1.78, (2, 7): 8.04, (2, 6): 6.45, (2, 5): 39.66, (2, 4): 37.42, (3, 1): 14.11, (3, 2): 7.99, (3, 7): 30.02, (3, 6): 30.17, (3, 5): 8.86, (3, 4): 8.86, (7, 1): 20.26, (7, 3): 36.05, (7, 5): 19.74, (7, 4): 23.95, (6, 1): 20.54, (6, 3): 41.84, (6, 5): 17.85, (6, 4): 19.77, (5, 0): 8.91, (5, 1): 44.44, (5, 2): 29.94, (5, 3): 2.46, (5, 7): 5.51, (5, 6): 8.74, (4, 0): 2.84, (4, 1): 43.49, (4, 2): 30.18, (4, 3): 2.66, (4, 7): 11.47, (4, 6): 9.36}


In [34]:
updated_ratios

{(0, 7): 1.66,
 (0, 6): 0.55,
 (0, 5): 48.62,
 (0, 4): 49.17,
 (1, 7): 1.37,
 (1, 6): 1.37,
 (1, 5): 52.05,
 (1, 4): 45.22,
 (2, 1): 6.64,
 (2, 3): 1.78,
 (2, 7): 8.04,
 (2, 6): 6.45,
 (2, 5): 39.66,
 (2, 4): 37.42,
 (3, 1): 14.11,
 (3, 2): 7.99,
 (3, 7): 30.02,
 (3, 6): 30.17,
 (3, 5): 8.86,
 (3, 4): 8.86,
 (7, 1): 20.26,
 (7, 3): 36.05,
 (7, 5): 19.74,
 (7, 4): 23.95,
 (6, 1): 20.54,
 (6, 3): 41.84,
 (6, 5): 17.85,
 (6, 4): 19.77,
 (5, 0): 8.91,
 (5, 1): 44.44,
 (5, 2): 29.94,
 (5, 3): 2.46,
 (5, 7): 5.51,
 (5, 6): 8.74,
 (4, 0): 2.84,
 (4, 1): 43.49,
 (4, 2): 30.18,
 (4, 3): 2.66,
 (4, 7): 11.47,
 (4, 6): 9.36}